// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjvlNAdsocCW3AGwMSUMUNXh-ADrHqTe4',
    appId: '1:20242419855:web:1b310772623888cf38a0fa',
    messagingSenderId: '20242419855',
    projectId: 'touristsafety-realtimedatabase',
    authDomain: 'touristsafety-realtimedatabase.firebaseapp.com',
    storageBucket: 'touristsafety-realtimedatabase.firebasestorage.app',
    measurementId: 'G-XVVB4BYQWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBkJIXDiLalMk9rHb4n02leUWZ3DSVKSM',
    appId: '1:20242419855:android:f22b3581181a3a3c38a0fa',
    messagingSenderId: '20242419855',
    projectId: 'touristsafety-realtimedatabase',
    storageBucket: 'touristsafety-realtimedatabase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5BccPSEyfIhoCPbIke5b28JPckhEVwrU',
    appId: '1:20242419855:ios:1229c75ece2492a338a0fa',
    messagingSenderId: '20242419855',
    projectId: 'touristsafety-realtimedatabase',
    storageBucket: 'touristsafety-realtimedatabase.firebasestorage.app',
    iosBundleId: 'com.example.touristSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5BccPSEyfIhoCPbIke5b28JPckhEVwrU',
    appId: '1:20242419855:ios:1229c75ece2492a338a0fa',
    messagingSenderId: '20242419855',
    projectId: 'touristsafety-realtimedatabase',
    storageBucket: 'touristsafety-realtimedatabase.firebasestorage.app',
    iosBundleId: 'com.example.touristSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjvlNAdsocCW3AGwMSUMUNXh-ADrHqTe4',
    appId: '1:20242419855:web:7d10b71ddc3ad6ac38a0fa',
    messagingSenderId: '20242419855',
    projectId: 'touristsafety-realtimedatabase',
    authDomain: 'touristsafety-realtimedatabase.firebaseapp.com',
    storageBucket: 'touristsafety-realtimedatabase.firebasestorage.app',
    measurementId: 'G-HE5ZSSCZW4',
  );
}
